INSERT INTO "plazer-user" ("userName", "userPassword", "FirstName", "LastName", "AddressL1", "AddressL2", "AddressL3", "Email", "gender", "skills", "DoB", "phone", "role", "image", "gitlink", "active")
VALUES
('john_doe', 'password123', 'John', 'Doe', '123 Main St', 'Apt 4B', NULL, 'john.doe@example.com', 'male', 'JavaScript, TypeScript', '1990-05-15', '555-1234', 'Member', 'path/to/image.jpg', 'https://github.com/johndoe', true),
('jane_smith', 'securepass', 'Jane', 'Smith', '456 Elm St', '', NULL, 'jane.smith@example.com', 'female', 'Project Management', '1985-07-20', '555-5678', 'Organization Admin', NULL, '', false),
('alex_jones', 'mypassword', 'Alex', 'Jones', '789 Oak St', 'Suite 300', 'Building A', 'alex.jones@example.com', 'unspecified', 'HR Management, Recruiting', '1992-11-02', '555-9012', 'HRManager', 'path/to/image2.jpg', 'https://github.com/alexjones', true),
('michael_brown', 'pass123', 'Michael', 'Brown', '123 Birch St', 'Floor 2', 'Room 205', 'michael.brown@example.com', 'male', 'Python, Data Analysis', '1988-08-25', '555-2222', 'Member', 'path/to/image3.jpg', 'https://github.com/michaelbrown', true),
('sarah_connor', 'pass456', 'Sarah', 'Connor', '789 Maple St', '', '', 'sarah.connor@example.com', 'female', 'Leadership, Strategic Planning', '1980-12-14', '555-3333', 'HRManager', NULL, '', false),
('william_clark', 'pass789', 'William', 'Clark', '456 Cedar St', 'Apt 12', NULL, 'william.clark@example.com', 'male', 'Java, Spring Boot', '1975-03-30', '555-4444', 'Organization Admin', 'path/to/image4.jpg', 'https://github.com/williamclark', true),
('emily_davis', 'pass101', 'Emily', 'Davis', '101 Pine St', '', '', 'emily.davis@example.com', 'female', 'Marketing, SEO', '1995-04-22', '555-5555', 'Member', '', 'https://github.com/emilydavis', true),
('james_taylor', 'pass202', 'James', 'Taylor', '303 Willow St', '', '', 'james.taylor@example.com', 'male', 'Node.js, React', '1985-07-12', '555-6666', 'HRManager', 'path/to/image5.jpg', 'https://github.com/jamestaylor', true),
('olivia_wilson', 'pass303', 'Olivia', 'Wilson', '202 Elm St', 'Apt 7C', NULL, 'olivia.wilson@example.com', 'female', 'Project Management, Agile', '1993-09-17', '555-7777', 'Organization Admin', 'path/to/image6.jpg', '', true),
('daniel_martin', 'pass404', 'Daniel', 'Martin', '404 Aspen St', 'Suite 5', '', 'daniel.martin@example.com', 'male', 'DevOps, Cloud Computing', '1990-10-10', '555-8888', 'Member', 'path/to/image7.jpg', 'https://github.com/danielmartin', true),
('sophia_moore', 'pass505', 'Sophia', 'Moore', '505 Chestnut St', '', '', 'sophia.moore@example.com', 'female', 'UI/UX Design', '1992-11-19', '555-9999', 'HRManager', '', 'https://github.com/sophiamoore', false),
('david_clarkson', 'pass606', 'David', 'Clarkson', '606 Hickory St', 'Floor 3', 'Room 309', 'david.clarkson@example.com', 'male', 'Cybersecurity', '1983-01-05', '555-1010', 'Organization Admin', 'path/to/image8.jpg', '', true);
